### ISSUE TITLE
devkit debug native-android error

### ISSUE THREAD

**Issue by mbaatartsogt** [gameclosure/devkit#225] opened 2015-05-11 13:16 UTC
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by softvar** [comment] 2015-05-12 21:11
Same here.

**Comment by fairfieldt** [comment] 2015-05-12 21:24
closing as a duplicate of #224

**Closed by fairfieldt** 2015-05-12 21:24 UTC
